name:                exercises
version:             0.1.0.0
github:              "jonathanlorimer/book-of-monads"
license:             BSD3
author:              "Jonathan Lorimer"
maintainer:          "jonathan_lorimer@mac.com"
copyright:           "2019 Jonathan Lorimer"

# Metadata used when publishing your package
# synopsis:            My solutions to the exercises in "Book of Monads"
# category:            Learning

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jonathanlorimer/exercises#readme>

default-extensions:
# Type Classes
- MultiParamTypeClasses
- FunctionalDependencies
- TypeSynonymInstances
- FlexibleContexts
- FlexibleInstances
- InstanceSigs
- UndecidableInstances
# Type System
- GADTs
- RankNTypes
- PolyKinds
- ScopedTypeVariables
- DataKinds
- KindSignatures
- TypeApplications
# Language Syntax
- LambdaCase
- TypeOperators
# Monads
- MonadComprehensions
- ApplicativeDo
# Deriving Functionality
- DeriveFunctor
- GeneralizedNewtypeDeriving
# Other
- TypeInType
- ConstraintKinds

dependencies:
- base >= 4.7 && < 5
- transformers
- logict
- stm

library:
  source-dirs: src

tests:
  exercises-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - exercises
